icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome4"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
